### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by Green-Sky** [monatis/clip.cpp#1]
Been following your progress with anticipation. Here are a couple of notes:
- the ggml submodule commit is nowhere to be found (even in your fork). had to manually checkout your master.
- hardcoded paths in examples/main ftw
- i got a _better_ model to work too. https://huggingface.co/laion/CLIP-ViT-B-32-laion2B-s34B-b79K
  but i had to modify the conversion script to read `"projection_dim"` from `config` instead (both times).
  quick similarity test with the apple picture:
  | model | `a dog` | `a red apple` |
  |-------|---------|---------------|
  | openai b32 | 0.228 | 0.341 |
  | laion b32 laion2b s34b b79k | 0.126 | 0.345 |
  
keep up the good work!

**Comment by monatis** [comment]
Thanks @Green-Sky for your attention and helpful feedback.

> had to manually checkout your master.

Unfortunately, this is because ggerganov/ggml#254 has not been merged yet. I'll checkout upstream master once it's merged. Maybe I can request Georgi's attention in that PR.

> i got a better model 

Thanks for trying this. It was also in my mind to try Laion's models, and seems that your modification sould work for both cases. I'll test it and modify the script to handle models from both sources.

> hardcoded paths in examples/main 

Sorry for that, I'm a little bit lazy to pass them from command line every time I'm running during the development 😶‍🌫️ The next commit today will remove them and parse them from command line instead.

I'll also share examples for zero-shot image labelling (one image vs. multiple texts), and semantic image search (multiple images vs. one textual query).

**Comment by Green-Sky** [comment]
> > had to manually checkout your master.
> 
> Unfortunately, this is because [ggerganov/ggml#254](https://github.com/ggerganov/ggml/pull/254) has not been merged yet. I'll checkout upstream master once it's merged. Maybe I can request Georgi's attention in that PR.

What I meant is that the commit should be one in your fork (for the pr). But even github cant find the exact commit, which means you never pushed the committed commit.

**Comment by monatis** [comment]
Got it. Fixed it now.
Also removed hardcoded stuff from the example and it reads from the command line. Run `./bin/main -h` for options.

Later today or tomorrow, I'll update the conversion script to handle models from Laion and craft better examples.

Please feel free to continue sharing your feedback, highly appreciated.

**Comment by Green-Sky** [comment]
closing this as done :)
